# Generated by Django 2.2.6 on 2019-10-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_log', models.DateTimeField()),
                ('row', models.PositiveIntegerField()),
            ],
        ),
    ]
