# Generated by Django 2.2.6 on 2019-10-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_displaydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaytopup',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
