# Generated by Django 2.2.6 on 2019-10-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_displaytopup_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='topup',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
