# Generated by Django 2.2.6 on 2019-11-01 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_topup_version'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisplayDate',
        ),
        migrations.RemoveField(
            model_name='displayincome',
            name='item',
        ),
        migrations.RemoveField(
            model_name='displaylogsheet',
            name='item',
        ),
        migrations.RemoveField(
            model_name='displaytempexpense',
            name='item',
        ),
        migrations.RemoveField(
            model_name='displaytopup',
            name='item',
        ),
        migrations.DeleteModel(
            name='DisplayExpense',
        ),
        migrations.DeleteModel(
            name='DisplayIncome',
        ),
        migrations.DeleteModel(
            name='DisplayLogSheet',
        ),
        migrations.DeleteModel(
            name='DisplayTempExpense',
        ),
        migrations.DeleteModel(
            name='DisplayTopUp',
        ),
    ]
