# Generated by Django 2.2.6 on 2019-10-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('user_superior', models.PositiveIntegerField(default=99)),
                ('date_log', models.DateTimeField()),
                ('version_log', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
