# Generated by Django 2.2.6 on 2019-11-04 11:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstart',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 11, 21, 41, 485329, tzinfo=utc)),
        ),
    ]
